### PR TITLE
Hyperparameter optomization

### PR DESCRIPTION
**Pull request by adamantivm**
Parameterizes the model and training a bit more and implements hyper-parameter optimization using Ray Tune.

See `optim.py`

Sample output:

```
Trial status: 12 TERMINATED
Current time: 2024-11-16 10:55:10. Total running time: 5min 58s
Logical resource usage: 0/20 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:G)
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Trial name                  status         n_epochs     dropout_p     iter     total time (s)        loss     test_loss │
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ train_adapter_8f96b_00000   TERMINATED            2           0.1        3            14.9845    0.820378       5.87947 │
│ train_adapter_8f96b_00001   TERMINATED            2           0.2        3            15.5275    2.31776        3.37903 │
│ train_adapter_8f96b_00002   TERMINATED            5           0.1        6            33.999    14.7283         5.3249  │
│ train_adapter_8f96b_00003   TERMINATED            5           0.2        6            34.0338    5.30956        3.75618 │
│ train_adapter_8f96b_00004   TERMINATED            2           0.1        3            14.6338    7.61944        4.34085 │
│ train_adapter_8f96b_00005   TERMINATED            2           0.2        3            15.0001    5.78725        4.44717 │
│ train_adapter_8f96b_00006   TERMINATED            5           0.1        6            34.4934    1.1779         3.52824 │
│ train_adapter_8f96b_00007   TERMINATED            5           0.2        6            35.6928    0.685025       4.59796 │
│ train_adapter_8f96b_00008   TERMINATED            2           0.1        3            15.9297    5.7282         3.07947 │
│ train_adapter_8f96b_00009   TERMINATED            2           0.2        3            16.2453    6.69282        3.25396 │
│ train_adapter_8f96b_00010   TERMINATED            5           0.1        6            36.0103   28.0095         9.17803 │
│ train_adapter_8f96b_00011   TERMINATED            5           0.2        6            34.5489   18.7464         6.74774 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### CODE REVIEW

**Comment by jonbinney** [comment]
Is each of the lines in that plot a complete training run with a different set of hyperparameters?

**Comment by adamantivm** [comment]
Yes, exactly.
Although these are just toy trials to make sure the thing works.

**Comment by adamantivm** [comment]
This is almost ready, except that for some unknown reason, now `train.py` using the same paramteres that were hardcoded before, not diverge instead of converging (for the train set).
Debugging why this happens ...

**Comment by adamantivm** [comment]
Ok, I fixed it! This is now ready for merge.

**Pull request merged**
