### PR TITLE
Fixes based on feedback on PR 4

### PR DESCRIPTION
**Pull request by jonbinney**

### CODE REVIEW

**Comment by alejandromarcu** [comment]
There are also similar issues in camera_control/src/camera_control/detection_control_widget.py

**Comment by jonbinney** [comment]
Added a commit to fix the issues in the detection control widget.

**Comment by jonbinney** [comment]
@alejandromarcu anything more i can fix on this?

**Comment by jonbinney** [comment]
I'm going to go ahead and merge because i'm changing these files for a future PR and don't want to create a merge problem.

**Comment by alejandromarcu** [comment]
That was it, thanks!

**Pull request merged**
